name: Flutter Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'
          
      - run: flutter create --platforms=android .
      - run: flutter pub get
      - run: flutter build apk --release
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expense-tracker-app
          path: build/app/outputs/apk/release/app-release.apk
